/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, x86_64-w64-mingw32-g++ 16.1.0 -march=nocona -msahf -mtune=generic -O2 -fstack-protector-strong -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "../rtl/agr_spi_bridge.sv:3.1-249.10" *)
module agr_spi_bridge(clk, rst_n, spi_csn, spi_sck, spi_mosi, spi_miso, bus_req, bus_we, bus_addr, bus_wdata, bus_rdata, bus_ready);
  (* src = "../rtl/agr_spi_bridge.sv:100.18-100.26" *)
  wire [15:0] addr_reg;
  wire addr_reg_SB_DFFE_Q_2_D;
  wire addr_reg_SB_DFFE_Q_3_D;
  wire addr_reg_SB_DFFE_Q_4_D;
  wire addr_reg_SB_DFFE_Q_5_D;
  wire addr_reg_SB_DFFE_Q_6_D;
  wire addr_reg_SB_DFFE_Q_7_D;
  wire addr_reg_SB_DFFE_Q_9_D;
  wire addr_reg_SB_DFFE_Q_9_E;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [1:0] addr_reg_SB_DFFE_Q_D;
  (* src = "../rtl/agr_spi_bridge.sv:17.31-17.39" *)
  output [15:0] bus_addr;
  wire [15:0] bus_addr;
  (* src = "../rtl/agr_spi_bridge.sv:20.31-20.40" *)
  input [7:0] bus_rdata;
  wire [7:0] bus_rdata;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_1_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_2_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_3_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_4_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_5_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_6_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [1:0] bus_rdata_SB_DFFER_D_7_Q;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] bus_rdata_SB_DFFER_D_Q;
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8" *)
  wire [7:0] bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O;
  (* src = "../rtl/agr_spi_bridge.sv:21.31-21.40" *)
  input bus_ready;
  wire bus_ready;
  (* src = "../rtl/agr_spi_bridge.sv:15.31-15.38" *)
  output bus_req;
  wire bus_req;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire bus_req_SB_DFFR_Q_D;
  (* src = "../rtl/agr_spi_bridge.sv:18.31-18.40" *)
  output [7:0] bus_wdata;
  wire [7:0] bus_wdata;
  (* src = "../rtl/agr_spi_bridge.sv:16.31-16.37" *)
  output bus_we;
  wire bus_we;
  (* src = "../rtl/agr_spi_bridge.sv:53.10-53.19" *)
  wire byte_done;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] byte_done_SB_DFFR_D_Q;
  (* src = "../rtl/agr_spi_bridge.sv:103.5-119.8" *)
  wire [2:0] byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] byte_done_SB_LUT4_O_I3;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2;
  (* abc9_carry = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/abc9_model.v:4.9-4.11" *)
  wire byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_CARRY_I1_CO;
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8" *)
  wire [2:0] byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_E;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_LUT4_I2_O;
  (* abc9_carry = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/abc9_model.v:8.8-8.10" *)
  wire byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3;
  (* src = "../rtl/agr_spi_bridge.sv:7.31-7.34" *)
  input clk;
  wire clk;
  (* src = "../rtl/agr_spi_bridge.sv:99.18-99.28" *)
  wire [7:0] cmd_commit;
  (* src = "../rtl/agr_spi_bridge.sv:122.5-129.8" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] cmd_commit_SB_DFFER_Q_D;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:122.5-129.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire cmd_commit_SB_DFFER_Q_E;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3;
  wire cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [1:0] cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2;
  (* src = "../rtl/agr_spi_bridge.sv:145.11-145.21" *)
  wire commit_raw;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] commit_raw_SB_DFFR_D_Q;
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8" *)
  wire commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_D;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_E;
  (* src = "../rtl/agr_spi_bridge.sv:148.5-153.8" *)
  wire commit_raw_SB_DFFR_Q_D;
  (* src = "../rtl/agr_spi_bridge.sv:27.17-27.22" *)
  (* unused_bits = "2" *)
  wire [2:0] cs_ff;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [3:0] cs_ff_SB_LUT4_I2_I3;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:103.5-119.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire cs_ff_SB_LUT4_I2_O;
  (* src = "../rtl/agr_spi_bridge.sv:44.10-44.17" *)
  wire cs_rise;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [1:0] cs_rise_SB_LUT4_O_I2;
  (* src = "../rtl/agr_spi_bridge.sv:45.10-45.16" *)
  wire mosi_d;
  (* src = "../rtl/agr_spi_bridge.sv:27.32-27.39" *)
  wire [2:0] mosi_ff;
  (* src = "../rtl/agr_spi_bridge.sv:8.31-8.36" *)
  input rst_n;
  wire rst_n;
  wire rst_n_SB_LUT4_I1_O;
  wire rst_n_SB_LUT4_I2_O;
  wire rst_n_SB_LUT4_I3_O;
  wire [6:0] rx_shift;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire rx_shift_SB_DFFER_Q_E;
  (* src = "../rtl/agr_spi_bridge.sv:27.24-27.30" *)
  (* unused_bits = "2" *)
  wire [2:0] sck_ff;
  (* src = "../rtl/agr_spi_bridge.sv:10.31-10.38" *)
  input spi_csn;
  wire spi_csn;
  (* src = "../rtl/agr_spi_bridge.sv:13.31-13.39" *)
  output spi_miso;
  wire spi_miso;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire spi_miso_SB_DFFER_Q_E;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O;
  (* src = "../rtl/agr_spi_bridge.sv:12.31-12.39" *)
  input spi_mosi;
  wire spi_mosi;
  (* src = "../rtl/agr_spi_bridge.sv:11.31-11.38" *)
  input spi_sck;
  wire spi_sck;
  (* src = "../rtl/agr_spi_bridge.sv:209.17-209.30" *)
  wire tx_data_valid;
  (* force_downto = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] tx_data_valid_SB_DFFER_D_Q;
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8" *)
  wire tx_data_valid_SB_DFFER_Q_D;
  (* defaultvalue = 1'h1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_sim.v:656.8-656.9" *)
  wire tx_data_valid_SB_DFFER_Q_E;
  (* src = "../rtl/agr_spi_bridge.sv:226.17-226.25" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] tx_shift;
  (* src = "../rtl/agr_spi_bridge.sv:101.18-101.27" *)
  wire [7:0] wdata_reg;
  wire wdata_reg_SB_DFFE_Q_E;
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_D[0]),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[15])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_1 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_9_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[14])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_10 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_2_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[5])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_11 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_3_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[4])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_12 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_4_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[3])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_13 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_5_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_14 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_6_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[1])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_15 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_7_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[0])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_2 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_2_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[13])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_2_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[4]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_2_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_3 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_3_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[12])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_3_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[3]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_3_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_4 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_4_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[11])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_4_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[2]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_4_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_5 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_5_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[10])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_5_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[1]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_5_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_6 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_6_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[9])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_6_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[0]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_6_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_7 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_7_D),
    .E(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(addr_reg[8])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_8 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_D[0]),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[7])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE addr_reg_SB_DFFE_Q_9 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_9_D),
    .E(addr_reg_SB_DFFE_Q_9_E),
    .Q(addr_reg[6])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_9_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[5]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_9_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) addr_reg_SB_DFFE_Q_9_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(byte_done_SB_DFFR_D_Q[0]),
    .I2(byte_done_SB_DFFR_D_Q[2]),
    .I3(byte_done_SB_DFFR_D_Q[3]),
    .O(addr_reg_SB_DFFE_Q_9_E)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER addr_reg_SB_DFFE_Q_D_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[6]),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_D[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q (
    .C(clk),
    .D(addr_reg[15]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[15])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_1 (
    .C(clk),
    .D(addr_reg[14]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[14])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_10 (
    .C(clk),
    .D(addr_reg[5]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[5])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_11 (
    .C(clk),
    .D(addr_reg[4]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[4])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_12 (
    .C(clk),
    .D(addr_reg[3]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[3])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_13 (
    .C(clk),
    .D(addr_reg[2]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_14 (
    .C(clk),
    .D(addr_reg[1]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[1])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_15 (
    .C(clk),
    .D(addr_reg[0]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[0])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_2 (
    .C(clk),
    .D(addr_reg[13]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[13])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_3 (
    .C(clk),
    .D(addr_reg[12]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[12])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_4 (
    .C(clk),
    .D(addr_reg[11]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[11])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_5 (
    .C(clk),
    .D(addr_reg[10]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[10])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_6 (
    .C(clk),
    .D(addr_reg[9]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[9])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_7 (
    .C(clk),
    .D(addr_reg[8]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[8])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_8 (
    .C(clk),
    .D(addr_reg[7]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[7])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_addr_SB_DFFE_Q_9 (
    .C(clk),
    .D(addr_reg[6]),
    .E(rst_n_SB_LUT4_I2_O),
    .Q(bus_addr[6])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D (
    .C(clk),
    .D(bus_rdata[7]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_1 (
    .C(clk),
    .D(bus_rdata[6]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_1_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) bus_rdata_SB_DFFER_D_1_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_1_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_1_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[6])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_2 (
    .C(clk),
    .D(bus_rdata[5]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_2_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) bus_rdata_SB_DFFER_D_2_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_2_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_2_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[5])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_3 (
    .C(clk),
    .D(bus_rdata[4]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_3_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) bus_rdata_SB_DFFER_D_3_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_3_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_3_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[4])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_4 (
    .C(clk),
    .D(bus_rdata[3]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_4_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) bus_rdata_SB_DFFER_D_4_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_4_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_4_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[3])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_5 (
    .C(clk),
    .D(bus_rdata[2]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_5_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) bus_rdata_SB_DFFER_D_5_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_5_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_5_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_6 (
    .C(clk),
    .D(bus_rdata[1]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_6_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hccf0)
  ) bus_rdata_SB_DFFER_D_6_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_6_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_6_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[1])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_rdata_SB_DFFER_D_7 (
    .C(clk),
    .D(bus_rdata[0]),
    .E(bus_ready),
    .Q(bus_rdata_SB_DFFER_D_7_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) bus_rdata_SB_DFFER_D_7_Q_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(bus_rdata_SB_DFFER_D_7_Q[0]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(bus_rdata_SB_DFFER_D_Q[0]),
    .I2(bus_rdata_SB_DFFER_D_Q[1]),
    .I3(cs_rise),
    .O(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[7])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR bus_req_SB_DFFR_Q (
    .C(clk),
    .D(bus_req_SB_DFFR_Q_D),
    .Q(bus_req),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcc0c)
  ) bus_req_SB_DFFR_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(commit_raw_SB_DFFR_D_Q[0]),
    .I2(commit_raw_SB_DFFR_D_Q[1]),
    .I3(cmd_commit[7]),
    .O(bus_req_SB_DFFR_Q_D)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q (
    .C(clk),
    .D(wdata_reg[7]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[7])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_1 (
    .C(clk),
    .D(wdata_reg[6]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[6])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_2 (
    .C(clk),
    .D(wdata_reg[5]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[5])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_3 (
    .C(clk),
    .D(wdata_reg[4]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[4])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_4 (
    .C(clk),
    .D(wdata_reg[3]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[3])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_5 (
    .C(clk),
    .D(wdata_reg[2]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_6 (
    .C(clk),
    .D(wdata_reg[1]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[1])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE bus_wdata_SB_DFFE_Q_7 (
    .C(clk),
    .D(wdata_reg[0]),
    .E(rst_n_SB_LUT4_I1_O),
    .Q(bus_wdata[0])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER bus_we_SB_DFFER_Q (
    .C(clk),
    .D(cmd_commit[7]),
    .E(bus_req_SB_DFFR_Q_D),
    .Q(bus_we),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR byte_done_SB_DFFR_D (
    .C(clk),
    .D(byte_done),
    .Q(byte_done_SB_DFFR_D_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:103.5-119.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER byte_done_SB_DFFR_D_Q_SB_DFFER_Q (
    .C(clk),
    .D(byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D[0]),
    .E(cs_ff_SB_LUT4_I2_O),
    .Q(byte_done_SB_DFFR_D_Q[2]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0020)
  ) byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D_SB_LUT4_O (
    .I0(byte_done_SB_DFFR_D_Q[2]),
    .I1(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .I2(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .I3(cs_rise),
    .O(byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0012)
  ) byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D_SB_LUT4_O_1 (
    .I0(byte_done_SB_DFFR_D_Q[2]),
    .I1(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .I2(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .I3(cs_rise),
    .O(byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00d9)
  ) byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D_SB_LUT4_O_2 (
    .I0(byte_done_SB_DFFR_D_Q[2]),
    .I1(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .I2(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .I3(cs_rise),
    .O(byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) byte_done_SB_DFFR_D_Q_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .I3(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .O(byte_done_SB_DFFR_D_Q[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) byte_done_SB_LUT4_O (
    .I0(1'h0),
    .I1(tx_data_valid_SB_DFFER_D_Q[1]),
    .I2(sck_ff[1]),
    .I3(byte_done_SB_LUT4_O_I3[2]),
    .O(byte_done)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc000)
  ) byte_done_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1[2]),
    .I2(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2[2]),
    .I3(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3),
    .O(byte_done_SB_LUT4_O_I3[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1_SB_DFFER_Q (
    .C(clk),
    .D(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D[2]),
    .E(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_E),
    .Q(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1[2]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0bb0)
  ) byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1_SB_LUT4_I2 (
    .I0(cs_rise_SB_LUT4_O_I2[0]),
    .I1(cs_ff[1]),
    .I2(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1[2]),
    .I3(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_CARRY_I1_CO),
    .O(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D[2])
  );
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4" *)
  SB_CARRY byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_CARRY_I1 (
    .CI(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3),
    .CO(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_CARRY_I1_CO),
    .I0(1'h0),
    .I1(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q (
    .C(clk),
    .D(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D[1]),
    .E(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_E),
    .Q(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2[2]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00cf)
  ) byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(cs_rise_SB_LUT4_O_I2[0]),
    .I2(cs_ff[1]),
    .I3(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3),
    .O(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hcf00)
  ) byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(cs_rise_SB_LUT4_O_I2[0]),
    .I2(cs_ff[1]),
    .I3(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_LUT4_I2_O[2]),
    .O(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2f22)
  ) byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_E_SB_LUT4_O (
    .I0(tx_data_valid_SB_DFFER_D_Q[1]),
    .I1(sck_ff[1]),
    .I2(cs_rise_SB_LUT4_O_I2[0]),
    .I3(cs_ff[1]),
    .O(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_E)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:64.29-64.40|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/arith_map.v:62.5-70.4|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2[2]),
    .I3(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3),
    .O(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_LUT4_I2_O[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3_SB_DFFER_Q (
    .C(clk),
    .D(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_D[0]),
    .E(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_E),
    .Q(byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:122.5-129.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER cmd_commit_SB_DFFER_Q (
    .C(clk),
    .D(cmd_commit_SB_DFFER_Q_D[7]),
    .E(cmd_commit_SB_DFFER_Q_E),
    .Q(cmd_commit[7]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) cmd_commit_SB_DFFER_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(addr_reg_SB_DFFE_Q_D[0]),
    .I3(cs_rise),
    .O(cmd_commit_SB_DFFER_Q_D[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2f22)
  ) cmd_commit_SB_DFFER_Q_E_SB_LUT4_O (
    .I0(cs_rise_SB_LUT4_O_I2[0]),
    .I1(cs_ff[1]),
    .I2(byte_done_SB_DFFR_D_Q[2]),
    .I3(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3[3]),
    .O(cmd_commit_SB_DFFER_Q_E)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(byte_done_SB_DFFR_D_Q[2]),
    .I3(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3[3]),
    .O(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000c)
  ) cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(byte_done_SB_DFFR_D_Q[0]),
    .I2(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .I3(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .O(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3[3])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:103.5-119.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q (
    .C(clk),
    .D(byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D[2]),
    .E(cs_ff_SB_LUT4_I2_O),
    .Q(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:103.5-119.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_DFFER_Q_1 (
    .C(clk),
    .D(byte_done_SB_DFFR_D_Q_SB_DFFER_Q_D[1]),
    .E(cs_ff_SB_LUT4_I2_O),
    .Q(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:155.5-160.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR commit_raw_SB_DFFR_D (
    .C(clk),
    .D(commit_raw),
    .Q(commit_raw_SB_DFFR_D_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:168.5-203.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER commit_raw_SB_DFFR_D_Q_SB_DFFER_Q (
    .C(clk),
    .D(commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_D),
    .E(commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_E),
    .Q(commit_raw_SB_DFFR_D_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(bus_ready),
    .I3(cs_rise),
    .O(commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hffae)
  ) commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_E_SB_LUT4_O (
    .I0(bus_ready),
    .I1(commit_raw_SB_DFFR_D_Q[0]),
    .I2(cmd_commit[7]),
    .I3(cs_rise),
    .O(commit_raw_SB_DFFR_D_Q_SB_DFFER_Q_E)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:148.5-153.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR commit_raw_SB_DFFR_Q (
    .C(clk),
    .D(commit_raw_SB_DFFR_Q_D),
    .Q(commit_raw),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8200)
  ) commit_raw_SB_DFFR_Q_D_SB_LUT4_O (
    .I0(byte_done_SB_DFFR_D_Q[0]),
    .I1(cmd_commit[7]),
    .I2(byte_done_SB_DFFR_D_Q[2]),
    .I3(byte_done_SB_DFFR_D_Q[3]),
    .O(commit_raw_SB_DFFR_Q_D)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:10.57-10.103" *)
  SB_DFFS cs_ff_SB_DFFS_D (
    .C(clk),
    .D(cs_ff[1]),
    .Q(cs_rise_SB_LUT4_O_I2[0]),
    .S(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:10.57-10.103" *)
  SB_DFFS cs_ff_SB_DFFS_Q (
    .C(clk),
    .D(cs_ff[0]),
    .Q(cs_ff[1]),
    .S(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:10.57-10.103" *)
  SB_DFFS cs_ff_SB_DFFS_Q_1 (
    .C(clk),
    .D(spi_csn),
    .Q(cs_ff[0]),
    .S(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0cae)
  ) cs_ff_SB_LUT4_I2 (
    .I0(byte_done_SB_DFFR_D_Q[0]),
    .I1(cs_rise_SB_LUT4_O_I2[0]),
    .I2(cs_ff[1]),
    .I3(cs_ff_SB_LUT4_I2_I3[3]),
    .O(cs_ff_SB_LUT4_I2_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0c0)
  ) cs_ff_SB_LUT4_I2_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(byte_done_SB_DFFR_D_Q[2]),
    .I2(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[0]),
    .I3(cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O_I2[1]),
    .O(cs_ff_SB_LUT4_I2_I3[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) cs_rise_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(cs_rise_SB_LUT4_O_I2[0]),
    .I3(cs_ff[1]),
    .O(cs_rise)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:75.5-84.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER mosi_d_SB_DFFER_D (
    .C(clk),
    .D(mosi_d),
    .E(byte_done),
    .Q(addr_reg_SB_DFFE_Q_7_D),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR mosi_d_SB_DFFR_Q (
    .C(clk),
    .D(mosi_ff[1]),
    .Q(mosi_d),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR mosi_ff_SB_DFFR_Q (
    .C(clk),
    .D(mosi_ff[0]),
    .Q(mosi_ff[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR mosi_ff_SB_DFFR_Q_1 (
    .C(clk),
    .D(spi_mosi),
    .Q(mosi_ff[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc000)
  ) rst_n_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(rst_n),
    .I2(commit_raw_SB_DFFR_D_Q[0]),
    .I3(cmd_commit[7]),
    .O(rst_n_SB_LUT4_I1_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) rst_n_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(rst_n),
    .I3(bus_req_SB_DFFR_Q_D),
    .O(rst_n_SB_LUT4_I2_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:12.34-13.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) rst_n_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(rst_n),
    .O(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q (
    .C(clk),
    .D(rx_shift[3]),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[4]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q_1 (
    .C(clk),
    .D(rx_shift[2]),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[3]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q_2 (
    .C(clk),
    .D(rx_shift[1]),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[2]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q_3 (
    .C(clk),
    .D(rx_shift[0]),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q_4 (
    .C(clk),
    .D(mosi_d),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q_5 (
    .C(clk),
    .D(rx_shift[5]),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[6]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:55.5-67.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER rx_shift_SB_DFFER_Q_6 (
    .C(clk),
    .D(rx_shift[4]),
    .E(rx_shift_SB_DFFER_Q_E),
    .Q(rx_shift[5]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR sck_ff_SB_DFFR_Q (
    .C(clk),
    .D(sck_ff[0]),
    .Q(sck_ff[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR sck_ff_SB_DFFR_Q_1 (
    .C(clk),
    .D(spi_sck),
    .Q(sck_ff[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q (
    .C(clk),
    .D(tx_shift[7]),
    .E(spi_miso_SB_DFFER_Q_E),
    .Q(spi_miso),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf300)
  ) spi_miso_SB_DFFER_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(cs_rise_SB_LUT4_O_I2[0]),
    .I2(cs_ff[1]),
    .I3(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3[2]),
    .O(spi_miso_SB_DFFER_Q_E)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfb08)
  ) spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3 (
    .I0(tx_data_valid),
    .I1(cs_rise_SB_LUT4_O_I2[0]),
    .I2(cs_ff[1]),
    .I3(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3[2]),
    .O(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[6]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E_1 (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[5]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_1_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E_2 (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[4]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_2_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E_3 (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[3]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_3_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E_4 (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[2]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_4_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E_5 (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[1]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_5_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_DFFER_E_6 (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[0]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(bus_rdata_SB_DFFER_D_6_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_O (
    .I0(1'h0),
    .I1(tx_data_valid_SB_DFFER_D_Q[0]),
    .I2(tx_data_valid_SB_DFFER_D_Q[1]),
    .I3(sck_ff[1]),
    .O(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER tx_data_valid_SB_DFFER_D (
    .C(clk),
    .D(tx_data_valid),
    .E(cs_rise),
    .Q(tx_data_valid_SB_DFFER_D_Q[0]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:29.5-39.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:9.57-9.103" *)
  SB_DFFR tx_data_valid_SB_DFFER_D_Q_SB_DFFR_Q (
    .C(clk),
    .D(sck_ff[1]),
    .Q(tx_data_valid_SB_DFFER_D_Q[1]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2022)
  ) tx_data_valid_SB_DFFER_D_Q_SB_LUT4_I0 (
    .I0(tx_data_valid_SB_DFFER_D_Q[1]),
    .I1(sck_ff[1]),
    .I2(cs_rise_SB_LUT4_O_I2[0]),
    .I3(cs_ff[1]),
    .O(rx_shift_SB_DFFER_Q_E)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:210.5-222.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER tx_data_valid_SB_DFFER_Q (
    .C(clk),
    .D(tx_data_valid_SB_DFFER_Q_D),
    .E(tx_data_valid_SB_DFFER_Q_E),
    .Q(tx_data_valid),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0fff)
  ) tx_data_valid_SB_DFFER_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(tx_data_valid),
    .I3(cs_rise),
    .O(tx_data_valid_SB_DFFER_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hfccc)
  ) tx_data_valid_SB_DFFER_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(bus_ready),
    .I2(tx_data_valid),
    .I3(cs_rise),
    .O(tx_data_valid_SB_DFFER_Q_E)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:229.5-247.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:14.63-14.116" *)
  SB_DFFER tx_shift_SB_DFFER_Q (
    .C(clk),
    .D(bus_rdata_SB_DFFER_D_Q_SB_LUT4_I1_O[7]),
    .E(spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3_SB_LUT4_I3_O),
    .Q(tx_shift[7]),
    .R(rst_n_SB_LUT4_I3_O)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_D[0]),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[7])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_1 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_9_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[6])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_2 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_2_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[5])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_3 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_3_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[4])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_4 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_4_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[3])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_5 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_5_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[2])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_6 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_6_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[1])
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/agr_spi_bridge.sv:132.5-140.8|C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE wdata_reg_SB_DFFE_Q_7 (
    .C(clk),
    .D(addr_reg_SB_DFFE_Q_7_D),
    .E(wdata_reg_SB_DFFE_Q_E),
    .Q(wdata_reg[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "C:\\msys64\\ucrt64\\bin\\../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc000)
  ) wdata_reg_SB_DFFE_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(byte_done_SB_DFFR_D_Q[0]),
    .I2(byte_done_SB_DFFR_D_Q[2]),
    .I3(byte_done_SB_DFFR_D_Q[3]),
    .O(wdata_reg_SB_DFFE_Q_E)
  );
  assign bus_rdata_SB_DFFER_D_6_Q[2] = cs_rise;
  assign tx_data_valid_SB_DFFER_D_Q[2] = sck_ff[1];
  assign addr_reg_SB_DFFE_Q_D[1] = cs_rise;
  assign byte_done_SB_LUT4_O_I3[1:0] = { sck_ff[1], tx_data_valid_SB_DFFER_D_Q[1] };
  assign { byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2[3], byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2[1:0] } = { byte_done_SB_LUT4_O_I3_SB_LUT4_O_I3, 2'h0 };
  assign byte_done_SB_DFFR_D_Q[1] = cmd_commit[7];
  assign cmd_commit_SB_DFFER_Q_E_SB_LUT4_O_I3[2:0] = { byte_done_SB_DFFR_D_Q[2], cs_ff[1], cs_rise_SB_LUT4_O_I2[0] };
  assign byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_LUT4_I2_O[1:0] = { cs_ff[1], cs_rise_SB_LUT4_O_I2[0] };
  assign bus_rdata_SB_DFFER_D_7_Q[1] = cs_rise;
  assign cs_ff_SB_LUT4_I2_I3[2:0] = { cs_ff[1], cs_rise_SB_LUT4_O_I2[0], byte_done_SB_DFFR_D_Q[0] };
  assign bus_rdata_SB_DFFER_D_5_Q[2] = cs_rise;
  assign commit_raw_SB_DFFR_D_Q[2] = cmd_commit[7];
  assign bus_rdata_SB_DFFER_D_4_Q[2] = cs_rise;
  assign spi_miso_SB_DFFER_Q_E_SB_LUT4_O_I3[1:0] = { cs_ff[1], cs_rise_SB_LUT4_O_I2[0] };
  assign bus_rdata_SB_DFFER_D_3_Q[2] = cs_rise;
  assign cs_rise_SB_LUT4_O_I2[1] = cs_ff[1];
  assign { byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1[3], byte_done_SB_LUT4_O_I3_SB_LUT4_O_I1[1:0] } = { byte_done_SB_LUT4_O_I3_SB_LUT4_O_I2_SB_CARRY_I1_CO, cs_ff[1], cs_rise_SB_LUT4_O_I2[0] };
  assign bus_rdata_SB_DFFER_D_2_Q[2] = cs_rise;
  assign bus_rdata_SB_DFFER_D_1_Q[2] = cs_rise;
  assign bus_rdata_SB_DFFER_D_Q[2] = cs_rise;
  assign cmd_commit[6:0] = 7'hxx;
  assign mosi_ff[2] = mosi_d;
endmodule
