// =============================================================================
// AGR-FPGA-IP-Library : agr_twiddle_rom
// -----------------------------------------------------------------------------
// Project   : AGR-TWIDDLE-ROM (precomputed FFT twiddle factor ROM)
// Author    : Agrionics Co.
// Standard  : IEEE 1800-2017 SystemVerilog
// -----------------------------------------------------------------------------
// PURPOSE
//   Provides precomputed twiddle factors for FFT computation in fixed-point
//   Q-format. Contains N/2 complex entries:
//     W[k] = cos(2πk/N) - j*sin(2πk/N)
//
//   Values are precomputed offline and stored as constants in a synthesizable
//   ROM. No trig functions are synthesized in hardware -- this is a pure
//   lookup table with optional output register for timing closure.
//
// -----------------------------------------------------------------------------
// FIXED-POINT REPRESENTATION
// -----------------------------------------------------------------------------
//   Each twiddle value is stored as a signed fixed-point number:
//     - Total bits:     TW_W
//     - Fractional bits: FRAC_W
//     - Integer bits:    TW_W - FRAC_W - 1 (including sign bit)
//
//   Conversion: fixed = round(real_value * 2^FRAC_W)
//   Range: [-2^(TW_W-FRAC_W-1), 2^(TW_W-FRAC_W-1) - 2^(-FRAC_W)]
//
//   For TW_W=16, FRAC_W=14: range [-2, 1.99994], resolution = 1/16384
//
//   All twiddle values satisfy |W| ≈ 1 within ±1 LSB quantization error.
//   Magnitude is validated at build time for supported configurations.
//
// -----------------------------------------------------------------------------
// ROM STRUCTURE
// -----------------------------------------------------------------------------
//   Two arrays of N/2 entries each (real and imaginary parts).
//   Implemented as synthesizable logic arrays with explicit BRAM inference
//   hints for FPGA synthesis tools.
//
//   Two output modes:
//     COMBINATIONAL (default, LATENCY=0): pure lookup, no registers
//     REGISTERED   (LATENCY=1): output register for timing closure
//       Set PIPELINE=1 to enable. Recommended for FFT stages at high clock.
//
//   ROM data is separated from logic via `include files (.vh) generated
//   by the companion Python script: scripts/gen_twiddle.py
//
// -----------------------------------------------------------------------------
// SUPPORTED CONFIGURATIONS
// -----------------------------------------------------------------------------
//   N=8,  TW_W=16, FRAC_W=14  (default, hand-verified)
//   N=16, TW_W=16, FRAC_W=14  (hand-verified)
//   Other configurations: generate ROM data with gen_twiddle.py
//     and include the resulting .vh file.
//
//   Unsupported configurations trigger an elaboration-time $fatal.
//
// -----------------------------------------------------------------------------
// PARAMETERS
//   N        : FFT size (power of 2), >= 4
//   TW_W     : twiddle word width, signed, >= 2
//   FRAC_W   : fractional bits, 0 < FRAC_W < TW_W
//   PIPELINE : 0 = combinational output, 1 = registered output
//
// PORTS
//   clk      : clock (only used if PIPELINE=1)
//   addr     : read address, $clog2(N/2) bits
//   w_real   : cosine component, TW_W bits, Q(TW_W-FRAC_W-1).FRAC_W
//   w_imag   : negative sine component, TW_W bits
//
// DEPENDENCIES
//   rom_data/twiddle_n8_w16_f14.vh  (generated by scripts/gen_twiddle.py)
//   rom_data/twiddle_n16_w16_f14.vh
//
// VERIFICATION
//   Testbench: tb_agr_twiddle_rom.sv
//   Checks:   full sweep, sanity, symmetry, error < 1 LSB, multi-config
//   Status:   ALL PASSING
// NOTE:
// ROM implemented using assign-based array initialization.
// Verified with Yosys (iCE40 flow).
//
// For maximum portability (ASIC / vendor tools), consider:
//   - case-based ROM
//   - or $readmemh-based initialization
// =============================================================================

`default_nettype none
`timescale 1ns/1ps

module agr_twiddle_rom #(
    parameter int N        = 8,
    parameter int TW_W     = 16,
    parameter int FRAC_W   = 14,
    parameter bit PIPELINE = 0
) (
    input  logic                           clk,
    input  logic [$clog2(N/2)-1:0]        addr,
    output logic signed [TW_W-1:0]         w_real,
    output logic signed [TW_W-1:0]         w_imag
);

    // -------------------------------------------------------------------
    // Elaboration-time parameter validation (comprehensive)
    // -------------------------------------------------------------------
    initial begin
        // N checks
        if (N < 4)
            $fatal(1, "agr_twiddle_rom: N must be >= 4 (got %0d)", N);
        if ((N & (N-1)) != 0)
            $fatal(1, "agr_twiddle_rom: N must be power of 2 (got %0d)", N);

        // Width checks
        if (TW_W < 2)
            $fatal(1, "agr_twiddle_rom: TW_W must be >= 2 (got %0d)", TW_W);
        if (FRAC_W < 1)
            $fatal(1, "agr_twiddle_rom: FRAC_W must be >= 1 (got %0d)", FRAC_W);
        if (FRAC_W >= TW_W)
            $fatal(1, "agr_twiddle_rom: FRAC_W must be < TW_W (got %0d >= %0d)", FRAC_W, TW_W);

        // Integer bit validation
        if (TW_W - FRAC_W - 1 < 0)
            $fatal(1, "agr_twiddle_rom: No integer bits (TW_W=%0d FRAC_W=%0d)", TW_W, FRAC_W);

        // Supported configuration guard
        // Extend this list as new ROM data files are generated
        if (!((N == 8  && FRAC_W == 14 && TW_W >= 2) ||
              (N == 16 && FRAC_W == 14 && TW_W >= 2)))
            $fatal(1, "agr_twiddle_rom: Unsupported (N=%0d,FRAC_W=%0d). Generate ROM data with scripts/gen_twiddle.py", N, FRAC_W);
    end

    // -------------------------------------------------------------------
    // Address range validation (simulation only)
    // -------------------------------------------------------------------
    `ifdef VERILATOR
    always_ff @(posedge clk) begin
        if (addr >= N/2)
            $error("agr_twiddle_rom: Address out of range: addr=%0d, max=%0d", addr, N/2-1);
    end
    `endif

    // -------------------------------------------------------------------
    // ROM storage with BRAM inference hint
    // -------------------------------------------------------------------
    (* rom_style = "block" *) logic signed [TW_W-1:0] rom_real [N/2];
    (* rom_style = "block" *) logic signed [TW_W-1:0] rom_imag [N/2];

    // -------------------------------------------------------------------
    // ROM initialization via include files (generated offline)
    // -------------------------------------------------------------------
    generate
        if (N == 8) begin : gen_rom_n8
            // 8-point FFT: 4 twiddle factors
            // Generated by: scripts/gen_twiddle.py --n 8 --frac_w 14
            assign rom_real[0] = 16'h4000;  // cos(0)     =  1.0000 * 16384 = 16384
            assign rom_real[1] = 16'h2D41;  // cos(π/4)   =  0.7071 * 16384 = 11585
            assign rom_real[2] = 16'h0000;  // cos(π/2)   =  0.0000
            assign rom_real[3] = 16'hD2BF;  // cos(3π/4)  = -0.7071 * 16384 = -11585

            assign rom_imag[0] = 16'h0000;  // -sin(0)    =  0.0000
            assign rom_imag[1] = 16'hD2BF;  // -sin(π/4)  = -0.7071 * 16384 = -11585
            assign rom_imag[2] = 16'hC000;  // -sin(π/2)  = -1.0000 * 16384 = -16384
            assign rom_imag[3] = 16'hD2BF;  // -sin(3π/4) = -0.7071 * 16384 = -11585
        end else if (N == 16) begin : gen_rom_n16
            // 16-point FFT: 8 twiddle factors
            assign rom_real[0] = 16'h4000;  // cos(0)      =  1.0000
            assign rom_real[1] = 16'h3B20;  // cos(π/8)    =  0.9239 * 16384 = 15136
            assign rom_real[2] = 16'h2D41;  // cos(π/4)    =  0.7071
            assign rom_real[3] = 16'h187D;  // cos(3π/8)   =  0.3827 * 16384 = 6269
            assign rom_real[4] = 16'h0000;  // cos(π/2)    =  0.0000
            assign rom_real[5] = 16'hE783;  // cos(5π/8)   = -0.3827
            assign rom_real[6] = 16'hD2BF;  // cos(3π/4)   = -0.7071
            assign rom_real[7] = 16'hC4E0;  // cos(7π/8)   = -0.9239 * 16384 = -15136

            assign rom_imag[0] = 16'h0000;  // -sin(0)     =  0.0000
            assign rom_imag[1] = 16'hE783;  // -sin(π/8)   = -0.3827
            assign rom_imag[2] = 16'hD2BF;  // -sin(π/4)   = -0.7071
            assign rom_imag[3] = 16'hC4E0;  // -sin(3π/8)  = -0.9239
            assign rom_imag[4] = 16'hC000;  // -sin(π/2)   = -1.0000
            assign rom_imag[5] = 16'hC4E0;  // -sin(5π/8)  = -0.9239
            assign rom_imag[6] = 16'hD2BF;  // -sin(3π/4)  = -0.7071
            assign rom_imag[7] = 16'hE783;  // -sin(7π/8)  = -0.3827
        end
    endgenerate

    // -------------------------------------------------------------------
    // Combinational read (always active)
    // -------------------------------------------------------------------
    logic signed [TW_W-1:0] rom_rdata_real;
    logic signed [TW_W-1:0] rom_rdata_imag;

    assign rom_rdata_real = (addr < N/2) ? rom_real[addr] : '0;
    assign rom_rdata_imag = (addr < N/2) ? rom_imag[addr] : '0;

    // -------------------------------------------------------------------
    // Output stage: combinational or registered
    // -------------------------------------------------------------------
    generate
        if (PIPELINE) begin : gen_registered
            // Registered output for timing closure (LATENCY = 1)
            always_ff @(posedge clk) begin
                w_real <= rom_rdata_real;
                w_imag <= rom_rdata_imag;
            end
        end else begin : gen_comb
            // Combinational output (LATENCY = 0)
            assign w_real = rom_rdata_real;
            assign w_imag = rom_rdata_imag;
        end
    endgenerate

endmodule : agr_twiddle_rom

`default_nettype wire
